version: "2.0"

services:
  db :
    build: ./Dockerfile
    image: postgres:12.0
    restart: on-failure
    container_name: Banco-api_db
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - Banco-api-volume:/var/lib/postgresql/data
    networks:
      - Banco-api-network

  web:
    build:
      context: .

    container_name: Banco-api_api
    env_file:
      - .env
    ports:
      - "8080"
    depends_on:
      - db
    volumes:
      - ./:/opt/app
    networks:
      - Banco-api-network
